language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g yarn
- cp ./src/example.config.js ./src/config.js
- printenv 
install:
- yarn
script:
- yarn build
- yarn lint
- yarn test
before_install:
- openssl aes-256-cbc -K $encrypted_4f23b46f1ec6_key -iv $encrypted_4f23b46f1ec6_iv
  -in .env.enc -out .env -d
